# Python CircleCI 2.0 configuration file
version: 2

jobs:

  build:
    docker:
      - image: themattrix/tox

    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run tests
          command: tox -e py37-test
    - store_artifacts:
        path: results
      - store_artifacts:
          path: ./log
          destination: logs-file

  html-docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install apt packages
          command: |
            sudo apt update
            sudo apt install -y graphviz
      - run:
          name: Install Python dependencies
          command: pip install tox --user
      - run:
          name: Make sure style checks pass
          command: tox -e codestyle
      - run:
          name: Build Docs
          command: tox -e build_docs -- -j=4
      - store_artifacts:
          path: docs/_build/html

workflows:
  version: 2
  tests_and_docs:
    jobs:
      - html-docs
      - build
